### ISSUE TITLE
Couple of questions

### ISSUE THREAD

**Issue by kennyklee** [maravento/blackweb#1]
Hey there. Great work here!

Couple of questions.

1. What are the sources for the data?  Is it from all sites listed under 'Data Sheet'?
2. How often are you planning to update these?  I hope it's automated. :)

**Comment by maravento** [comment]
Thank you for your interest in our project.
1. Check [Sources](https://github.com/maravento/blackweb#sources)
2. create a bash and schedule it in the crontab:
```
#!/usr/bin/env bash
dstblackweb="/path_to_acl/blackweb.txt" # change with your own path
wget -q -N https://raw.githubusercontent.com/maravento/blackweb/master/blackweb.tar.gz && cat blackweb.tar.gz* | tar xzf -
wget -q -N https://raw.githubusercontent.com/maravento/blackweb/master/checksum.md5
md5sum blackweb.txt | awk '{print $1}' && cat checksum.md5 | awk '{print $1}'
cp -f blackweb.txt $dstblackweb
rm -rfv blackweb* checksum*

sudo crontab -e
@monthly /path_to_script/blackweb_update.sh
```
