### ISSUE TITLE
bwupdate.sh not working

### ISSUE THREAD

**Issue by seyfullahkilic** [maravento/blackweb#12]
Hi,

While I'm running the "bwupdate.sh" on Linux machine, not finished (terminal output > "Downloading Blocklists..."). 

Maybe, some URLs not respond.

**Comment by elico** [comment]
@seyfullahkilic  A simple connect timeout for the curl command might help avoiding this.

**Comment by maravento** [comment]
Blackweb is already optimized and without errors. So `bwupdate.sh` is not necessary for user to run it. Note that this process can take time and consume a lot of hardware and bandwidth resources, therefore it is recommended to use test equipment.
We have changed the method. Now `bwupdate.sh` does the following:
```
wget --no-check-certificate --timeout=10 --tries=1 --method=HEAD "$1" &>/dev/null
    if [ $? -eq 0 ]; then
		    $wgetd "$1" -O - >> bwtmp/bw
	    else
		    echo ERROR "$1"
    fi
```
First check if the link exists. If it does not exist, it indicates an ERROR. If it exists, it runs the variable `$wgetd` and download the links. Example:
```
wgetd='wget -q -c --no-check-certificate --retry-connrefused --timeout=10 --tries=4'
$wgetd 'http://adaway.org/hosts.txt'
```
Changes In commit [501d189](https://github.com/maravento/blackweb/commit/501d189289806bf10961b89cbd33a508f24b6387) 

Thanks for the contributions
