### ISSUE TITLE
TLDs blocked

### ISSUE THREAD

**Issue by fhd75** [maravento/blackweb#13]
Hello, Im starting with your project, it is amazing. I see you just added on blocked TLDs ".gov.com" since it is not a TLD and no one could want to block it, I suppose it was a mistake. The same with ".webcamsex" and ".comsex" which doesn't exist.
".gay" is used by the gay community, not only porn.  I would remove .download and .cash since are used for legal stuff too.
Anyway, I know that I can compile it myself the way I want it, but I think this suggestions contribute, thanks.

**Comment by maravento** [comment]
[it has been fixed](https://github.com/maravento/blackweb/commit/d47b018bcd7b50fc601cc00cbbc3c4aff6215682) Thanks for the contribution.
