### ISSUE TITLE
How often the blackweb.txt get updated?

### ISSUE THREAD

**Issue by drveresh** [maravento/blackweb#16]
Hi,

Is there any process or somebody updating the **blackweb.txt** file periodically to let the community to download and use it directly instead of letting them run scripts? If not, you may add me as a core committer and I can maintain it every few days.

Thanks!

**Comment by maravento** [comment]
Thank you for using the blackweb project.
Blackweb has a debugging process. We constantly have to go through lists to add and exclude urls, and check for structure and errors. It also requires dedicated hardware as it consumes resources. Therefore, each update requires time to release.
There is no specific time to release the update, but it will never be more than 2 months.
However, the update bash script is published, for those who don't want to wait for our update and decide to do it themselves.
Regards
