### ISSUE TITLE
Problem on ..dns.freak.de

### ISSUE THREAD

**Issue by ghislain-bernard** [maravento/blackweb#18]
HI,

Why double point for dns.freak.de ? an error ?

![Screenshot_2022-02-04_11-48-00](https://user-images.githubusercontent.com/37534566/152516359-0aa913ac-6ca0-48f1-ba0f-ea7cb316df1c.png)

Best regards

**Comment by maravento** [comment]
[fix it](https://github.com/maravento/blackweb/commit/285ab11bebeb48da010f03139978615f5124f887)

thanks for your contribution
