### ISSUE TITLE
Format file for opnsense/pfsense

### ISSUE THREAD

**Issue by likehopper** [maravento/blackweb#19]
First of all, congratulations on your work !
However, it might be nice to format the file for opnsense/pfsense which makes it easy to select categories.
( cf. http://dsi.ut-capitole.fr/blacklists/download/blacklists_for_pfsense.tar.gz )
Could this be a possible feature ?

**Comment by maravento** [comment]
Thanks for visiting us. 
Blackweb is a unified blocklist for squid-cache.
This project includes [Université Toulouse 1 Capitole - Blacklists UT1 - blacklists.tar.gz](https://dsi.ut-capitole.fr/blacklists/index_en.php) (check [SOURCES blocklist](https://github.com/maravento/blackweb?tab=readme-ov-file#blocklists))
But, if you want to have categories, you should consider other projects, like the one you mention.
