### ISSUE TITLE
Legitimate sites in blacklist

### ISSUE THREAD

**Issue by chiara-paci** [maravento/blackweb#21]
Hi.

I'm trying to implement blackweb in the proxy of one of my clients, but there is something I can't understand.

I activate it in a test environment, and it's blocking almost everything, including:
- well known sites like apache.org, docker.com, pypi.org, etc.;
- banks like unicredit.it;
- almost every italian provider (tiscali.it, virgilio.it, libero.it, etc.);
- governative institutions (sogei.it, rai.it, provincia.tn.it, etc.).

Why are they included? How can Sogei, owned by a ministry, be in a blacklist?

**Comment by maravento** [comment]
Thank you for your interest in Blackweb

BlackWeb is a project that collects and unifies public blocklists of domains. Therefore, if there are false positives, it is from one of the BlackWeb sources, described in [SOURCES](https://github.com/maravento/blackweb#blocklists)

The sites you just mentioned:


```
.apache.org
.docker.com
.libero.it
.provincia.tn.it
.pypi.org
.rai.it
.sogei.it
.tiscali.it
.unicredit.it
.virgilio.it
```

They have been reviewed and will be removed in the next BlackWeb update. But in the meantime, you can exclude them manually in the `allowurls.txt` ACL:

```
# Allow Rules for Domains
acl allowdomains dstdomain "/path_to/allowdomains.txt"
http_access allow allowdomains

# Block Rule for Blackweb
acl blackweb dstdomain "/path_to/blackweb.txt"
http_access deny blackweb
```

# Important: 
check https://github.com/maravento/blackweb#notice

**Comment by maravento** [comment]
fix it https://github.com/maravento/blackweb/commit/4d00724eaddb6d1466f9f3a8be566c542e3b7ea4

**Comment by centri-awilson** [comment]
amazon.com is included, which is a pain. Not sure if you would like a new issue?

**Comment by maravento** [comment]
> amazon.com is included, which is a pain. Not sure if you would like a new issue?

Thanks for reporting.

Just to clarify: blackweb is an automated compilation of multiple upstream blocklists rather than a hand-curated list itself. In this case, amazon.com is being flagged by external sources (such as txthinking and UT-Capitole).

However, we have added amazon.com to `debugwl.txt` (debug whitelist). It will be excluded starting with the next compiled update of blackweb.

Thanks for bringing this to our attention!

PS: You can verify the evidence.

```
wget https://raw.githubusercontent.com/maravento/blackweb/refs/heads/master/bwupdate/tools/checksources.sh
chmod +x checksources.sh
./checksources.sh

=== Check Sources ===
[?] Existing downloaded lists found.
    1) Search only (reuse existing lists)
    2) Re-download all lists
    3) Exit
Choose an option [1/2/3]: 1


[?] Enter domain to search, or 'q' to quit (e.g: kickass.to): amazon.com

2026-08-24 14:01:10 [*] Searching for 'amazon.com'...
2026-08-24 14:01:10 [+] Domain found in: https://raw.githubusercontent.com/txthinking/blackwhite/master/black.list
2026-08-24 14:01:10 [+] Domain found in: https://raw.githubusercontent.com/txthinking/bypass/master/china_domain.txt
2026-08-24 14:01:10 [+] Domain found in: http://dsi.ut-capitole.fr/blacklists/download/blacklists.tar.gz (extracted)
2026-08-24 14:01:10 checksources done at: lun 24 ago 2026 14:01:10 -05
```
