### ISSUE TITLE
Reason why certain urls are part of blackweb.tr.gz ?

### ISSUE THREAD

**Issue by strilok** [maravento/blackweb#22]
Hi Team,
             Please help me understand as to why certain urls like cbsbank.com, cbsnews.com are part of blackweb https://github.com/maravento/blackweb/blob/master/blackweb.tar.gz ?

Your response will help me understand if I should be using list of blocked urls from your site.

Regards

**Comment by maravento** [comment]
Please Read https://github.com/maravento/blackweb/issues/21#issuecomment-2110346516

**Comment by maravento** [comment]
fix it https://github.com/maravento/blackweb/commit/4d00724eaddb6d1466f9f3a8be566c542e3b7ea4
