### ISSUE TITLE
Warning: Potential Redundancy Issue in the Blacklist

### ISSUE THREAD

**Issue by Adansidi** [maravento/blackweb#24]
Hello~

We are a threat intelligence research group. In our recent research work, we referenced the blacklist you constructed. During our quality assessment of this blacklist, we found that there might be some redundant information.

Specifically, some domains may have expired or been safely resolved but are still present in the blacklist. In the July 2024 update, our evaluation of redundancy is as follows:

| Status | Rate |
|--------|-------|
| Hold | 0.80% |
| Pending | 1.68% |
| NXDOMAIN | 0.17% |
| Parked | 0.20% |
| Sinkholed | 0.03% |

For example, the domain grrrff2452.com has been sinkholed in our observation, but it still appears in the most recent blacklist update.

Considering the large size of your blacklist, the absolute scale of this redundant information can impact the deployment and use of the blacklist. We are curious if you check the domains in the blacklist during updates, or if it is possible to develop some basic quality assurance and optimization mechanisms in the future.

Thank you!

**Comment by maravento** [comment]
Thank you for your interest in blackweb

All domains are verified by [DNS lookup](https://github.com/maravento/blackweb#dns-loockup)

We recommend you read the project. Blackweb is not a blacklist, per se, but a project that compiles public blacklists, to make them compatible with [squid-cache](https://www.squid-cache.org/)

Check https://github.com/maravento/blackweb#notice

Regards
