### ISSUE TITLE
Git clone of blackweb goes to current directory

### ISSUE THREAD

**Issue by obbrc** [maravento/blackweb#3]
blackweb.sh assumes there is a directory ~/blackweb and files are installed there. However, git clone https://github.com/maravento/blackweb.git creates the directory on the current directory.  This works fine from crontab job, but if the script is executed from a different location, it checks out and downloads the files to loca directory. cd ~ before git clone would help to run this script from any location.
Please read the README carefully.

**Comment by maravento** [comment]
Thank you for your interest in our project.
We have updated the project, which solves your question
