### ISSUE TITLE
Nombres duplicados

### ISSUE THREAD

**Issue by duhow** [maravento/blackweb#4]
Hay algunos nombres que están duplicados pero en Mayúsculas (por ejemplo wtennis).
¿Se podrían cargar todos los nombres, pasar a minúsculas y quitar repetidos? Hay como 600+ casos.

**Comment by duhow** [comment]
Además hay como 4 dominios [DNS](https://es.wikipedia.org/wiki/Sistema_de_nombres_de_dominio#Entendiendo_las_partes_de_un_nombre_de_dominio) que superan los 63 carácteres por etiqueta, siendo nombres / dominios inválidos.

**Comment by maravento** [comment]
Actualizado. Verifica. Cualquier otro problema, no dudes en notificarnos. Saludos

**Comment by duhow** [comment]
La cosa es que he aprovechado la misma lista para usar directamente como servidor DNS en blanco, y he podido observar esos "fallos" que me decía. Adjunto archivo en cuanto sea posible con los fallos.

**Comment by duhow** [comment]
Comprobaré la nueva versión, muchas gracias!
