### ISSUE TITLE
Nueva lista de sitios a bloquear

### ISSUE THREAD

**Issue by ehames** [maravento/blackweb#5]
Encontré esta lista de dominios que se pueden bloquear a nivel de DNS o quizás también podrían incluirse en este proyecto
http://someonewhocares.org/hosts/hosts

Aquí hay más listas que se podrían agregar
https://dsi.ut-capitole.fr/blacklists/index_en.php
http://www.shallalist.de/

Gracias!

**Comment by maravento** [comment]
Hola Por favor, revisa la sección [Sources](https://github.com/maravento/blackweb#sources)
