### ISSUE TITLE
Download and Update script are not working

### ISSUE THREAD

**Issue by jamesfigueroa01** [maravento/blackweb#6]
Hello,

I am very interested in using your domain list but every time I try to run the download or update script, it is filled with errors(No such file or directory mostly). Even if I download and try to use just the blackweb.txt file form 2/8, it contains duplicates (subdomains). I am doing this on Ubuntu 16.03. Thank you for any help, much appreciated.

**Comment by elico** [comment]
@jamesfigueroa01 What file exactly are you running for the update?
I am working an an enhanced version which might help Squid-Cache users.

**Comment by maravento** [comment]
@jamesfigueroa01 Could you describe your problem better in order to help you and if it is possible to include screenshot?

**Comment by jamesfigueroa01** [comment]
I am on Ubuntu 16.04.3 LTS

here are my results:

> root@:~ wget https://raw.githubusercontent.com/maravento/blackweb/master/blackweb.sh -O /etc/init.d/blackweb.sh
> --2018-03-01 11:52:31--  https://raw.githubusercontent.com/maravento/blackweb/master/blackweb.sh
> Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
> Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: 1350 (1.3K) [text/plain]
> Saving to: ?/etc/init.d/blackweb.sh?
> 
> /etc/init.d/blackwe 100%[===================>]   1.32K  --.-KB/s    in 0s      
> 
> 2018-03-01 11:52:31 (85.2 MB/s) - ?/etc/init.d/blackweb.sh? saved [1350/1350]
> 
> root@:~ chown root:root /etc/init.d/blackweb.sh && sudo chmod +x /etc/init.d/blackweb.sh
> root@:~
> root@:~  /etc/init.d/blackweb.sh
> Download Blackweb ACL...
> /etc/init.d/blackweb.sh: line 34: cd: /root/bl: No such file or directory
> cat: 'blackweb.tar.gz*': No such file or directory
> 
> gzip: stdin: unexpected end of file
> tar: Child returned status 1
> tar: Error is not recoverable: exiting now
> OK
> 
> Checking Sum...
> md5sum: blackweb.txt: No such file or directory
> cat: blackweb.md5: No such file or directory
> Sum Matches
> OK
> Done

Am i doing something wrong? Sorry for the delay in responding

**Comment by maravento** [comment]
@jamesfigueroa01 Do not run the script in the **ROOT account**. Run it with sudo in the user account, as indicated in the instructions. Example:
user@user:~$ wget https://raw.githubusercontent.com/maravento/blackweb/master/blackweb.sh -O /etc/init.d/blackweb.sh
user@user:~$ sudo chown root:root /etc/init.d/blackweb.sh && sudo chmod +x /etc/init.d/blackweb.sh
user@user:~$ sudo /etc/init.d/blackweb.sh

**Comment by jamesfigueroa01** [comment]
here are the results for a non root user:

> administrator@:~$ sudo wget https://raw.githubusercontent.com/maravento/blackweb/master/blackweb.sh -O /etc/init.d/blackweb.sh
> --2018-03-01 13:22:13--  https://raw.githubusercontent.com/maravento/blackweb/master/blackweb.sh
> Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
> Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: 1350 (1.3K) [text/plain]
> Saving to: ?/etc/init.d/blackweb.sh?
> 
> /etc/init.d/blackwe 100%[===================>]   1.32K  --.-KB/s    in 0s      
> 
> 2018-03-01 13:22:13 (143 MB/s) - ?/etc/init.d/blackweb.sh? saved [1350/1350]
> 
> administrator@:~$ 
> administrator@:~$ sudo chown root:root /etc/init.d/blackweb.sh && sudo chmod +x /etc/init.d/blackweb.sh
> administrator@:~$ sudo /etc/init.d/blackweb.sh
> 
> Download Blackweb ACL...
> /etc/init.d/blackweb.sh: line 34: cd: /home/administrator/bl: No such file or directory
> cat: 'blackweb.tar.gz*': No such file or directory
> 
> gzip: stdin: unexpected end of file
> tar: Child returned status 1
> tar: Error is not recoverable: exiting now
> OK
> 
> Checking Sum...
> md5sum: blackweb.txt: No such file or directory
> cat: blackweb.md5: No such file or directory
> Sum Matches
> OK
> Done
> administrator@:~$ 

same result...

**Comment by maravento** [comment]
Fix it. try again

**Comment by jamesfigueroa01** [comment]
I removed the server name for privacy but its there, never edited .bashrc.

**Comment by maravento** [comment]
Login to a non-root account (normal user in the group "sudoers") and download Blackweb as indicated above and you will not have problems

**Comment by elico** [comment]
@maravento if you are indeed using this script then this directory should be created automatically by these lines:
- https://github.com/maravento/blackweb/blob/master/blackweb.sh#L23
- https://github.com/maravento/blackweb/blob/master/blackweb.sh#L27

To make  sure that happens when the script runs you should add "set -x" at:
- https://github.com/maravento/blackweb/blob/master/blackweb.sh#L15

and "set +x" at the end of the script, then run the script as sudo and quote the output here or in a gist.

**Comment by maravento** [comment]
@jamesfigueroa01 You can execute **from anywhere and from any account**.
`wget https://github.com/maravento/blackweb/raw/master/blackweb.sh && chmod +x blackweb.sh && ./blackweb.sh`

**Comment by elico** [comment]
@maravento a typo...
But, why use svn when you can use plain git?(just wondering)
And for @jamesfigueroa01 we still needs to know what happens at run-time and the "set -x" should help us understand what happens when the script runs.
It's pretty simple.

**Comment by maravento** [comment]
@elico There are many ways to download a github folder and we have chosen SVN (which may change in the future or not). Blackweb is an Open Source project. Anyone can make a fork and adapt it to their needs or preferences.

**Comment by maravento** [comment]
@jamesfigueroa01 We have updated the scripts [blackweb.sh](https://github.com/maravento/blackweb/blob/master/blackweb.sh) and [bwupdate.sh](https://github.com/maravento/blackweb/blob/master/update/bwupdate.sh) (Latest commit [6424c91](https://github.com/maravento/blackweb/commit/6424c9160260c1df3cd6080ec14be1c1f751c9c2) an hour ago) that solves the problem of the **bl** directory. Now you can execute the scripts **from anywhere** and **from any account**.

**Comment by elico** [comment]
@maravento I believe that this  blackweb.sh and bwupdate.sh scripts should not be help at /etc/init.d/ but at some place such as: /usr/local/bin/
and I also believe that a proper library for the bl should be held at /var/xyz/bl maybe /var/balckweb/bl
And these scripts should run under a crontab.
But it's my way of handling my servers so just take it as a recommendation.

**Comment by maravento** [comment]
@elico If you have any problem with the project, start a new **issue**, detailing the problem. We have previously answered your comments.

**Comment by jamesfigueroa01** [comment]
hey,

Sorry i have not been able to respond sooner. Unfortunately, here are the results:

> administrator@******:~$ wget https://github.com/maravento/blackweb/raw/master/blackweb.sh && sudo chmod +x blackweb.sh && sudo ./blackweb.sh
> --2018-03-13 11:28:27--  https://github.com/maravento/blackweb/raw/master/blackweb.sh
> Resolving github.com (github.com)... 192.30.253.112, 192.30.253.113
> Connecting to github.com (github.com)|192.30.253.112|:443... connected.
> HTTP request sent, awaiting response... 302 Found
> Location: https://raw.githubusercontent.com/maravento/blackweb/master/blackweb.sh [following]
> --2018-03-13 11:28:29--  https://raw.githubusercontent.com/maravento/blackweb/master/blackweb.sh
> Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
> Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: 1383 (1.4K) [text/plain]
> Saving to: ?blackweb.sh.2?
> 
> blackweb.sh.2       100%[===================>]   1.35K  --.-KB/s    in 0s      
> 
> 2018-03-13 11:28:30 (160 MB/s) - ?blackweb.sh.2? saved [1383/1383]
> 
> [sudo] password for administrator: 
> Download Blackweb ACL...
> ./blackweb.sh: line 34: cd: /home/administrator/bl: No such file or directory
> cat: 'blackweb.tar.gz*': No such file or directory
> 
> gzip: stdin: unexpected end of file
> tar: Child returned status 1
> tar: Error is not recoverable: exiting now
> OK
> 
> Checking Sum...
> md5sum: blackweb.txt: No such file or directory
> cat: blackweb.md5: No such file or directory
> Sum Matches
> OK
> 
> Done
> administrator@******:~$ 

>

**Comment by maravento** [comment]
Remove any previous script

**Comment by jamesfigueroa01** [comment]
I cleared the files in the administrator user account but no difference:

> administrator@******:~$ ls
> blackweb.sh  blackweb.sh.1  blackweb.sh.2
> administrator@********:~$ rm blackweb.sh
> administrator@********:~$ rm blackweb.sh.1
> administrator@********:~$ rm blackweb.sh.2 
> administrator@********:~$ ls
> administrator@********:~$ 
> administrator@********:~$ wget https://github.com/maravento/blackweb/raw/master/blackweb.sh && sudo chmod +x blackweb.sh && sudo ./blackweb.sh
> --2018-03-13 12:37:17--  https://github.com/maravento/blackweb/raw/master/blackweb.sh
> Resolving github.com (github.com)... 192.30.253.112, 192.30.253.113
> Connecting to github.com (github.com)|192.30.253.112|:443... connected.
> HTTP request sent, awaiting response... 302 Found
> Location: https://raw.githubusercontent.com/maravento/blackweb/master/blackweb.sh [following]
> --2018-03-13 12:37:17--  https://raw.githubusercontent.com/maravento/blackweb/master/blackweb.sh
> Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.200.133
> Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.200.133|:443... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: 1383 (1.4K) [text/plain]
> Saving to: ?blackweb.sh?
> 
> blackweb.sh         100%[===================>]   1.35K  --.-KB/s    in 0s      
> 
> 2018-03-13 12:37:17 (128 MB/s) - ?blackweb.sh? saved [1383/1383]
> 
> [sudo] password for administrator: 
> 
> Download Blackweb ACL...
> ./blackweb.sh: line 34: cd: /home/administrator/bl: No such file or directory
> cat: 'blackweb.tar.gz*': No such file or directory
> 
> gzip: stdin: unexpected end of file
> tar: Child returned status 1
> tar: Error is not recoverable: exiting now
> OK
> 
> Checking Sum...
> md5sum: blackweb.txt: No such file or directory
> cat: blackweb.md5: No such file or directory
> Sum Matches
> OK
> 
> Done
> administrator@*****:~$

**Comment by maravento** [comment]
We have updated the project. Please check the new procedures
