### ISSUE TITLE
MD5 Checksum file not matching the blackweb.txt

### ISSUE THREAD

**Issue by inxbit** [maravento/blackweb#9]
Following your instructions, it seems the MD5 file is not maintained and it fails the check.

[root@dev block]# wget -q -N https://raw.githubusercontent.com/maravento/blackweb/master/blackweb.tar.gz && cat blackweb.tar.gz* | tar xzf -
[root@dev block]# ls | grep blackweb
blackweb.sh
blackweb.tar.gz
blackweb.txt
[root@dev block]# wget -q -N https://raw.githubusercontent.com/maravento/blackweb/master/checksum.md5
[root@dev block]# ls | grep checksum
checksum.md5
[root@dev block]# md5sum blackweb.txt | awk '{print $1}' && cat checksum.md5 | awk '{print $1}'
967503818f84092d132f78027da9c61d
26440258542a93dc377e9e99d64ca392

My scripts are failing because of this, is there any plan to keep the md5 file updated?

Thanks in advance and best regards,

CD

**Comment by maravento** [comment]
MD5 verification is optional. If you want, just run:

`wget -q -N https://raw.githubusercontent.com/maravento/blackweb/master/blackweb.tar.gz && cat blackweb.tar.gz* | tar xzf -`
